version: '3.8'

services:
  angular:
    build: ./front/docker/angular
    volumes:
      - ./front/dist:/mnt/dist
  npm:
    build:
      context: ./front/docker/npm
      args:
        DEV_GID: ${DEV_GID:-1000}
        DEV_UID: ${DEV_UID:-1000}
    cap_add:
      # Mandatory to be able to run chrome without --no-sandbox option
      - SYS_ADMIN
    command: run install-build-watch
    environment:
      - CYPRESS_CACHE_FOLDER=/mnt/tkdo/.cache/Cypress
      - NG_CLI_ANALYTICS=false
      - NPM_CONFIG_CACHE=/mnt/tkdo/.cache/npm
    volumes:
      - ./:/mnt/tkdo
