#!/usr/bin/env bash

# Fichiers communs
tar -cvf tkdo.tar -C apache .

# Fichiers front
./npm-front run build --prod
tar -rvf tkdo.tar -C front/dist/tkdo .

# Fichiers api
./composer-api install
tar -rvf tkdo.tar --transform='s/\.prod$//' \
  ./api/{app,bin,logs/README.md,public,src,var/{cache,doctrine/{cache,proxy}}/.gitignore,vendor,.env.prod,*.php,composer.{json,lock}}

# Finalisation
gzip -f tkdo.tar
