services:
  angular:
    build: ./front/docker/angular
    volumes:
      - ./front/dist:/mnt/dist

  front:
    build: ./docker/front
    depends_on:
      - angular
      - slim-web
    ports:
      - 8080:80

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: tkdo
      MYSQL_USER: tkdo
      MYSQL_PASSWORD: mdptkdo
      MYSQL_ROOT_PASSWORD: mdproot
    healthcheck:
      test: >
        out=$$(mysqladmin ping -h localhost -P 3306 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD 2>&1);
        echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
      interval: 5s
      retries: 10
      start_interval: 1s
      start_period: 30s

  npm:
    build:
      context: ./front/docker/npm
      args:
        DEV_GID: ${DEV_GID:-1000}
        DEV_UID: ${DEV_UID:-1000}
    cap_add:
      # Mandatory to be able to run chrome without --no-sandbox option
      - SYS_ADMIN
    environment:
      - CYPRESS_CACHE_FOLDER=/mnt/tkdo/.cache/Cypress
      - NG_CLI_ANALYTICS=false
      - NPM_CONFIG_CACHE=/mnt/tkdo/.cache/npm
    volumes:
      - ./:/mnt/tkdo


  php-cli:
    build: docker/php-cli
    environment:
      HOME: /opt/tkdo
      XDG_CACHE_HOME: /opt/tkdo/.cache
      docker: "true"
      MAILHOG_BASE_URI: http://mailhog:8025/
      MHSENDMAIL_OPTIONS: --smtp-addr=mailhog:1025
      MYSQL_DATABASE: tkdo
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: mdptkdo
      MYSQL_PORT: 3306
      MYSQL_USER: tkdo
      TKDO_BASE_URI: http://slim-web
      TKDO_MAILER_FROM: noreply@slim
    profiles:
      - tools
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - .:/opt/tkdo
    working_dir: /opt/tkdo/api-v1

  slim-fpm:
    build: ./docker/slim-fpm
    depends_on:
      mysql:
        condition: service_healthy
      mailhog:
        condition: service_started
    environment:
      docker: "true"
      MHSENDMAIL_OPTIONS: --smtp-addr=mailhog:1025
      MYSQL_DATABASE: tkdo
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: mdptkdo
      MYSQL_PORT: 3306
      MYSQL_USER: tkdo
      TKDO_BASE_URI: http://slim-web
      TKDO_MAILER_FROM: noreply@slim
      WWW_GID: ${GID:-1000}
      WWW_UID: ${UID:-1000}
    volumes:
      - ./api-v1:/var/www/html
      - ./docker/slim-fpm/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint

  slim-web:
    depends_on:
      - slim-fpm
    image: nginx:1.27
    ports:
      - "8081:80"
    volumes:
      - ./api-v1:/var/www/html
      - ./docker/slim-web/default.conf:/etc/nginx/conf.d/default.conf

