#!/usr/bin/env bash

# Sauvegarde le paramétrage local non versionné
mkdir api_backup
mv api/.env* api_backup/
mkdir api_backup/auth
mv api/var/auth/{.gitignore,*.prod} api_backup/auth/
mv api/var/doctrine api_backup/

rm -r api

# See https://github.com/slimphp/Slim-Skeleton
# no use of ./composer here as we need composer to run at the repo root
docker compose run --rm --interactive --workdir /opt/tkdo composer create-project slim/slim-skeleton api

# Restaure le paramétrage local non versionné
mv api_backup/{auth,doctrine} api/var/
mv api_backup/.env* api/
rmdir api_backup
echo '/.env*' >> api/.gitignore

function lowercase {
  s=$1
  echo "$(tr '[:upper:]' '[:lower:]' <<< ${s:0:1})${s:1}"
}

ACTION_DIR=api/src/Application/Actions
DOMAIN_DIR=api/src/Domain
PERSISTENCE_DIR=api/src/Infrastructure/Persistence
ACTION_TEST_DIR=api/tests/Application/Actions
DOMAIN_TEST_DIR=api/tests/Domain
PERSISTENCE_TEST_DIR=api/tests/Infrastructure/Persistence

function copy-entity {
  name=$1
  lname=$(lowercase $name)
  
  # Replace User in comment lines by Xxx
  # Duplicate other lines with User, replacing User by the entity name in the 1st copy
  sed -Ee "s/(\/\/.*)Users?/\1Xxx/;s/InMemory/Doctrine/;/Users?/{h;s/Users?/${name}/g;p;g}" -i api/app/repositories.php

  # Consider lines containing ->group and the 3 following lines as a block 
  # Duplicate lines or group blocks with User, replacing User/user by the entity name in the 1st copy
  sed -Ee "/->group\('\/users?'/{N;N;N};/Users?/{h;s/Users?/${name}/g;s/\/users?/\/${lname}/g;p;g}" -i api/app/routes.php
  
  mkdir $ACTION_DIR/$name
  sed -Ee "s/Users?/$name/g;s/(\\\$\{?| |->)user/\1$lname/g;s/\/users?/\/$lname/g" $ACTION_DIR/User/UserAction.php > $ACTION_DIR/$name/${name}Action.php
  sed -Ee "s/Users?/$name/g;s/(\\\$\{?| |->)user/\1$lname/g;s/\/users?/\/$lname/g" $ACTION_DIR/User/ListUsersAction.php > $ACTION_DIR/$name/List${name}Action.php
  sed -Ee "s/Users?/$name/g;s/(\\\$\{?| |->)user/\1$lname/g;s/\/users?/\/$lname/g" $ACTION_DIR/User/ViewUserAction.php > $ACTION_DIR/$name/View${name}Action.php
  
  mkdir $DOMAIN_DIR/$name
  sed -Ee "s/Users?/$name/g;s/(\\\$\{?| |->)user/\1$lname/g;s/\/users?/\/$lname/g" $DOMAIN_DIR/User/User.php > $DOMAIN_DIR/$name/$name.php
  sed -Ee "s/Users?/$name/g;s/(\\\$\{?| |->)user/\1$lname/g;s/\/users?/\/$lname/g" $DOMAIN_DIR/User/UserNotFoundException.php > $DOMAIN_DIR/$name/${name}NotFoundException.php
  sed -Ee "s/Users?/$name/g;s/(\\\$\{?| |->)user/\1$lname/g;s/\/users?/\/$lname/g" $DOMAIN_DIR/User/UserRepository.php > $DOMAIN_DIR/$name/${name}Repository.php
  
  mkdir $PERSISTENCE_DIR/$name
  sed -Ee "s/Users?/$name/g;s/(\\\$\{?| |->)user/\1$lname/g;s/\/users?/\/$lname/g" $PERSISTENCE_DIR/User/InMemoryUserRepository.php > $PERSISTENCE_DIR/$name/InMemory${name}Repository.php
  
  mkdir $ACTION_TEST_DIR/$name
  sed -Ee "s/Users?/$name/g;s/(\\\$\{?| |->)user/\1$lname/g;s/\/users?/\/$lname/g" $ACTION_TEST_DIR/User/ListUserActionTest.php > $ACTION_TEST_DIR/$name/List${name}ActionTest.php
  sed -Ee "s/Users?/$name/g;s/(\\\$\{?| |->)user/\1$lname/g;s/\/users?/\/$lname/g" $ACTION_TEST_DIR/User/ViewUserActionTest.php > $ACTION_TEST_DIR/$name/View${name}ActionTest.php
  
  mkdir $DOMAIN_TEST_DIR/$name
  sed -Ee "s/Users?/$name/g;s/(\\\$\{?| |->)user/\1$lname/g;s/\/users?/\/$lname/g" $DOMAIN_TEST_DIR/User/UserTest.php > $DOMAIN_TEST_DIR/$name/${name}Test.php
  
  mkdir $PERSISTENCE_TEST_DIR/$name
  sed -Ee "s/Users?/$name/g;s/(\\\$\{?| |->)user/\1$lname/g;s/\/users?/\/$lname/g" $PERSISTENCE_TEST_DIR/User/InMemoryUserRepositoryTest.php > $PERSISTENCE_TEST_DIR/$name/InMemory${name}RepositoryTest.php
}

function delete-entity-template {
  sed -Ee "/User/d" -i api/app/repositories.php
  sed -Ee "/->group/{N;N;N};/User/d" -i api/app/routes.php

  rm -f $ACTION_DIR/User/ListUsersAction.php
  rm -f $ACTION_DIR/User/UserAction.php
  rm -f $ACTION_DIR/User/ViewUserAction.php
  rmdir $ACTION_DIR/User

  rm -f $DOMAIN_DIR/User/User.php
  rm -f $DOMAIN_DIR/User/UserNotFoundException.php
  rm -f $DOMAIN_DIR/User/UserRepository.php
  rmdir $DOMAIN_DIR/User

  rm -f $PERSISTENCE_DIR/User/InMemoryUserRepository.php
  rmdir $PERSISTENCE_DIR/User

  rm -f $ACTION_TEST_DIR/User/ListUserActionTest.php
  rm -f $ACTION_TEST_DIR/User/ViewUserActionTest.php
  rmdir $ACTION_TEST_DIR/User

  rm -f $DOMAIN_TEST_DIR/User/UserTest.php
  rmdir $DOMAIN_TEST_DIR/User

  rm -f $PERSISTENCE_TEST_DIR/User/InMemoryUserRepositoryTest.php
  rmdir $PERSISTENCE_TEST_DIR/User
}

MIDDLEWARE_DIR=api/src/Application/Middleware 

function copy-middleware {
  name=$1
  sed -Ee s/SessionMiddleware/${name}Middleware/g $MIDDLEWARE_DIR/SessionMiddleware.php > $MIDDLEWARE_DIR/${name}Middleware.php
  sed -Ee "s/((.*)SessionMiddleware(.*))/\1\n\2${name}Middleware\3/" -i api/app/middleware.php
}

function delete-middleware-template {
  rm -f $MIDDLEWARE_DIR/SessionMiddleware.php
  sed -Ee "/SessionMiddleware/d" -i api/app/middleware.php
}

copy-middleware Auth
delete-middleware-template

copy-entity Connexion
copy-entity Utilisateur
copy-entity Occasion
copy-entity Idee
copy-entity Resultat
delete-entity-template

# slim-skeleton is not yet PHP >8.1 compatible, so upgrade it ourselves
./composer require php:^8.4 php-di/php-di:^7.0
./composer remove --dev \
  jangregor/phpstan-prophecy \
  phpspec/prophecy-phpunit \
  phpstan/extension-installer \
  phpstan/phpstan \
  phpunit/phpunit
./composer config allow-plugins.phpstan/extension-installer true
./composer require --dev --no-interaction \
  jangregor/phpstan-prophecy \
  phpspec/prophecy-phpunit \
  phpstan/extension-installer \
  phpstan/phpstan \
  phpunit/phpunit \
  rector/rector

cat > api/rector.php <<EOF
<?php

use Rector\Config\RectorConfig;
use Rector\PHPUnit\Set\PHPUnitSetList;

return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/app',
        __DIR__ . '/public',
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ])
    ->withPhpSets()
    ->withSets([
        PHPUnitSetList::PHPUNIT_90,
        PHPUnitSetList::PHPUNIT_100,
        PHPUnitSetList::PHPUNIT_110,
    ]);
EOF
sed -E '/"test":/{h;s/"test":.*/"rector": "rector",/;p;g}' -i api/composer.json
./composer run rector
./composer test -- --migrate-configuration

./composer test
