# Resolve GitHub PR Comments for Completed Action Items
# Post-Fix Workflow - Run after implementing fixes for action items
name: resolve-pr-comments
description: "Mark GitHub PR comments as resolved for completed action items. Run after implementing fixes and marking action items as [x] complete."
author: "BMad + Project Customization"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
planning_artifacts: "{config_source}:planning_artifacts"
implementation_artifacts: "{config_source}:implementation_artifacts"
output_folder: "{implementation_artifacts}"
sprint_status: "{implementation_artifacts}/sprint-status.yaml"

# Workflow components
installed_path: "{project-root}/_bmad/_config/custom/workflows/resolve-pr-comments"
instructions: "{installed_path}/instructions.xml"
validation: false
template: false

variables:
  project_context: "**/project-context.md"
  story_dir: "{implementation_artifacts}"
  claude_readme: "{project-root}/.claude/README.md"

standalone: true
