<?php

declare(strict_types=1);

namespace Test\Unit\Builder;

use App\Appli\ModelAdaptor\GroupeAdaptor;
use PHPUnit\Framework\TestCase;
use Test\Builder\GroupeBuilder;

/**
 * Unit tests for GroupeBuilder.
 *
 * Tests verify the builder pattern API works correctly
 * and produces valid GroupeAdaptor entities.
 */
class GroupeBuilderTest extends TestCase
{
    #[\Override]
    public function setUp(): void
    {
        GroupeBuilder::resetCounter();
    }

    public function testUnGroupeReturnsBuilderInstance(): void
    {
        $builder = GroupeBuilder::unGroupe();

        $this->assertInstanceOf(GroupeBuilder::class, $builder);
    }

    public function testDefaultNomIsAutoGenerated(): void
    {
        $builder = GroupeBuilder::unGroupe();

        $values = $builder->getValues();
        $this->assertEquals('Groupe 1', $values['nom']);
    }

    public function testCounterIncrementsForEachBuilder(): void
    {
        $builder1 = GroupeBuilder::unGroupe();
        $builder2 = GroupeBuilder::unGroupe();

        $this->assertEquals('Groupe 1', $builder1->getValues()['nom']);
        $this->assertEquals('Groupe 2', $builder2->getValues()['nom']);
    }

    public function testWithNomSetsCustomName(): void
    {
        $builder = GroupeBuilder::unGroupe()
            ->withNom('Famille Dupont');

        $values = $builder->getValues();
        $this->assertEquals('Famille Dupont', $values['nom']);
    }

    public function testWithNomReturnsSelfForChaining(): void
    {
        $builder = GroupeBuilder::unGroupe();

        $result = $builder->withNom('Test');

        $this->assertSame($builder, $result);
    }

    public function testDefaultArchiveIsFalse(): void
    {
        $builder = GroupeBuilder::unGroupe();

        $values = $builder->getValues();
        $this->assertFalse($values['archive']);
    }

    public function testWithArchiveSetsFlag(): void
    {
        $builder = GroupeBuilder::unGroupe()
            ->withArchive(true);

        $values = $builder->getValues();
        $this->assertTrue($values['archive']);
    }

    public function testWithArchiveReturnsSelfForChaining(): void
    {
        $builder = GroupeBuilder::unGroupe();

        $result = $builder->withArchive(true);

        $this->assertSame($builder, $result);
    }

    public function testResetCounterResetsToZero(): void
    {
        GroupeBuilder::unGroupe(); // Counter = 1
        GroupeBuilder::unGroupe(); // Counter = 2

        GroupeBuilder::resetCounter();

        $builder = GroupeBuilder::unGroupe();
        $this->assertEquals('Groupe 1', $builder->getValues()['nom']);
    }

    public function testBuildReturnsGroupeAdaptor(): void
    {
        $groupe = GroupeBuilder::unGroupe()->build();

        $this->assertInstanceOf(GroupeAdaptor::class, $groupe);
    }

    public function testBuildSetsNomAndDateCreation(): void
    {
        $groupe = GroupeBuilder::unGroupe()
            ->withNom('Test Groupe')
            ->build();

        $this->assertEquals('Test Groupe', $groupe->getNom());
        $this->assertNotNull($groupe->getDateCreation());
    }

    public function testBuildSetsArchiveFlag(): void
    {
        $groupe = GroupeBuilder::unGroupe()
            ->withArchive(true)
            ->build();

        $this->assertTrue($groupe->getArchive());
    }

    public function testFluentApiChaining(): void
    {
        $builder = GroupeBuilder::unGroupe()
            ->withNom('Test Groupe')
            ->withArchive(true);

        $values = $builder->getValues();

        $this->assertEquals('Test Groupe', $values['nom']);
        $this->assertTrue($values['archive']);
    }
}
