<?php

declare(strict_types=1);

namespace Test\Unit\Builder;

use PHPUnit\Framework\TestCase;
use Test\Builder\GroupeBuilder;

/**
 * Unit tests for GroupeBuilder scaffold.
 *
 * Tests verify the builder pattern API works correctly.
 * The actual entity creation (build/persist) will be tested when
 * GroupeAdaptor entity is implemented in Story 2.1.
 */
class GroupeBuilderTest extends TestCase
{
    #[\Override]
    public function setUp(): void
    {
        // Reset counter before each test for isolation
        GroupeBuilder::resetCounter();
    }

    public function testUnGroupeReturnsBuilderInstance(): void
    {
        $builder = GroupeBuilder::unGroupe();

        $this->assertInstanceOf(GroupeBuilder::class, $builder);
    }

    public function testDefaultNomIsAutoGenerated(): void
    {
        $builder = GroupeBuilder::unGroupe();

        $values = $builder->getValues();
        $this->assertEquals('Groupe 1', $values['nom']);
    }

    public function testCounterIncrementsForEachBuilder(): void
    {
        $builder1 = GroupeBuilder::unGroupe();
        $builder2 = GroupeBuilder::unGroupe();

        $this->assertEquals('Groupe 1', $builder1->getValues()['nom']);
        $this->assertEquals('Groupe 2', $builder2->getValues()['nom']);
    }

    public function testWithNomSetsCustomName(): void
    {
        $builder = GroupeBuilder::unGroupe()
            ->withNom('Famille Dupont');

        $values = $builder->getValues();
        $this->assertEquals('Famille Dupont', $values['nom']);
    }

    public function testWithNomReturnsSelfForChaining(): void
    {
        $builder = GroupeBuilder::unGroupe();

        $result = $builder->withNom('Test');

        $this->assertSame($builder, $result);
    }

    public function testWithDescriptionSetsDescription(): void
    {
        $builder = GroupeBuilder::unGroupe()
            ->withDescription('Un groupe familial');

        $values = $builder->getValues();
        $this->assertEquals('Un groupe familial', $values['description']);
    }

    public function testWithDescriptionReturnsSelfForChaining(): void
    {
        $builder = GroupeBuilder::unGroupe();

        $result = $builder->withDescription('Test');

        $this->assertSame($builder, $result);
    }

    public function testDefaultDescriptionIsNull(): void
    {
        $builder = GroupeBuilder::unGroupe();

        $values = $builder->getValues();
        $this->assertNull($values['description']);
    }

    public function testWithMembresSetsMembersList(): void
    {
        $membre1 = new \stdClass();
        $membre2 = new \stdClass();

        $builder = GroupeBuilder::unGroupe()
            ->withMembres([$membre1, $membre2]);

        $values = $builder->getValues();
        $this->assertCount(2, $values['membres']);
        $this->assertSame($membre1, $values['membres'][0]);
        $this->assertSame($membre2, $values['membres'][1]);
    }

    public function testWithMembresReturnsSelfForChaining(): void
    {
        $builder = GroupeBuilder::unGroupe();

        $result = $builder->withMembres([]);

        $this->assertSame($builder, $result);
    }

    public function testAddMembreAppendsMember(): void
    {
        $membre1 = new \stdClass();
        $membre2 = new \stdClass();

        $builder = GroupeBuilder::unGroupe()
            ->addMembre($membre1)
            ->addMembre($membre2);

        $values = $builder->getValues();
        $this->assertCount(2, $values['membres']);
    }

    public function testAddMembreReturnsSelfForChaining(): void
    {
        $builder = GroupeBuilder::unGroupe();

        $result = $builder->addMembre(new \stdClass());

        $this->assertSame($builder, $result);
    }

    public function testDefaultMembresIsEmptyArray(): void
    {
        $builder = GroupeBuilder::unGroupe();

        $values = $builder->getValues();
        $this->assertIsArray($values['membres']);
        $this->assertEmpty($values['membres']);
    }

    public function testResetCounterResetsToZero(): void
    {
        GroupeBuilder::unGroupe(); // Counter = 1
        GroupeBuilder::unGroupe(); // Counter = 2

        GroupeBuilder::resetCounter();

        $builder = GroupeBuilder::unGroupe();
        $this->assertEquals('Groupe 1', $builder->getValues()['nom']);
    }

    public function testBuildThrowsRuntimeException(): void
    {
        $builder = GroupeBuilder::unGroupe();

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('scaffold');

        $builder->build();
    }

    public function testPersistThrowsRuntimeException(): void
    {
        $builder = GroupeBuilder::unGroupe();
        $em = $this->createMock(\Doctrine\ORM\EntityManager::class);

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('scaffold');

        $builder->persist($em);
    }

    public function testFluentApiChaining(): void
    {
        $membre = new \stdClass();

        $builder = GroupeBuilder::unGroupe()
            ->withNom('Test Groupe')
            ->withDescription('Description')
            ->addMembre($membre);

        $values = $builder->getValues();

        $this->assertEquals('Test Groupe', $values['nom']);
        $this->assertEquals('Description', $values['description']);
        $this->assertCount(1, $values['membres']);
    }
}
