# Review and Respond to GitHub PR Comments
# Post-Review Workflow - Run after adversarial code-review completes with "Create action items"
name: review-pr-comments
description: "Post-review workflow that merges GitHub PR comments into story action items and responds to all unresolved comments. Run after code-review chooses option 2 (Create action items)."
author: "BMad + Project Customization"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
planning_artifacts: "{config_source}:planning_artifacts"
implementation_artifacts: "{config_source}:implementation_artifacts"
output_folder: "{implementation_artifacts}"
sprint_status: "{implementation_artifacts}/sprint-status.yaml"

# Workflow components
installed_path: "{project-root}/_bmad/_config/custom/workflows/review-pr-comments"
instructions: "{installed_path}/instructions.xml"
validation: false
template: false

variables:
  project_context: "**/project-context.md"
  story_dir: "{implementation_artifacts}"
  claude_readme: "{project-root}/.claude/README.md"

standalone: true
