version: '3.8'

services:
  front:
    build: ./docker/front
    depends_on:
      - angular
      - npm
      - slim
      - slim-cli
    ports:
      - 8080:80
  npm:
    command: run install-build-watch -- --configuration production
