#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

if [ "$1" = "php-fpm" ]; then
	# dynamically adjust the www pool user & group
	sed -i \
		-e "s/^user = .*/user = ${WWW_UID:-www-data}/" \
		-e "s/^group = .*/group = ${WWW_GID:-www-data}/" \
		/usr/local/etc/php-fpm.d/www.conf
fi

exec "$@"
